language: php

php:
  - 7.1

servive:
  - mysql

before_script:
#  - pecl install memcached --disable-memcached-sasl
#  - echo "extension=<extension>.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo apt install php-memcached
  - mysql -e "create database VDS"
  - composer install
  - php artisan migrate
